In [3]:

import numpy as np
# Khai báo vector và ma trận
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])

# a) Phép toán cơ bản trên vector và ma trận (15 điểm)
tong = A + B
tich_so = 3 * A - 2 * B

# b) Tính tích vô hướng A · B và góc giữa hai vector (tính bằng độ, làm tròn đến 3 chữ số thập phân). (5 điểm)
dot_product = np.dot(A, B)
cos_theta = dot_product / (np.linalg.norm(A) * np.linalg.norm(B))
goc_do = np.degrees(np.arccos(cos_theta))

# c) Tính tích ma trận CTC (chuyển vị của C nhân với C). (5 điểm)
CTC = np.dot(C.T, C)

tong, tich_so, dot_product, round(goc_do, 3), CTC

(array([3, 3, 1, 5]),
 array([  4, -11,  13, -10]),
 -8,
 108.376,
 array([[ 5,  0, -1],
        [ 0, 14, 10],
        [-1, 10, 17]]))