In [2]:
import numpy as np
R = np.array([[1, -2, 3],
              [2, 0, 1],
              [-1, 1, 4]])
b = np.array([10, 8, 7])

# a) Giải hệ phương trình Rx = b bằng phương pháp np.linalg.solve(). (8 điểm)
x1 = np.linalg.solve(R, b)

# b) Xác định xem ma trận R có khả nghịch không. Nếu có, tính ma trận nghịch đảo và dùng nó để giải lại hệ. So sánh hai nghiệm. (7 điểm)
try:
    R_inv = np.linalg.inv(R)
    x2 = R_inv @ b
    kha_nghich = True
except np.linalg.LinAlgError:
    x2 = None
    R_inv = None
    kha_nghich = False

# c) Tính chuẩn Frobenius của ma trận R. (5 điểm)
fro_norm = np.linalg.norm(R, 'fro')

x1, kha_nghich, R_inv, x2, fro_norm

(array([2.7826087 , 0.04347826, 2.43478261]),
 True,
 array([[-0.04347826,  0.47826087, -0.08695652],
        [-0.39130435,  0.30434783,  0.2173913 ],
        [ 0.08695652,  0.04347826,  0.17391304]]),
 array([2.7826087 , 0.04347826, 2.43478261]),
 6.082762530298219)