In [2]:
import numpy as np
P = np.array([[2, 1, 0, 1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])

b = np.array([4, 7, 9, 5])

# a) a) Tìm ma trận nghịch đảo của P. Nếu không khả nghịch, giải thích lý do. (10 điểm)
try:
    P_inv = np.linalg.inv(P)
    kha_nghich = True
except np.linalg.LinAlgError:
    kha_nghich = False
    P_inv = None

# b) Giải hệ phương trình trên bằng cách sử dụng nghịch đảo ma trận. (10 điểm)
if kha_nghich:
    x = P_inv @ b

#  c) Kiểm tra nghiệm bằng cách nhân ma trận P với vector nghiệm và so sánh với vector hằng số. (5 điểm)
kiem_tra = P @ x if kha_nghich else None

kha_nghich, P_inv, x, kiem_tra

(True,
 array([[ 0.48837209, -0.09302326,  0.02325581, -0.20930233],
        [ 0.03488372,  0.27906977, -0.06976744,  0.12790698],
        [-0.11627907,  0.06976744,  0.23255814, -0.09302326],
        [-0.01162791, -0.09302326,  0.02325581,  0.29069767]]),
 array([0.46511628, 2.10465116, 1.65116279, 0.96511628]),
 array([4., 7., 9., 5.]))