In [2]:
import numpy as np
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

eig_vals, eig_vecs = np.linalg.eig(Q)

# Chuẩn hóa các vector riêng
eig_vecs_norm = eig_vecs / np.linalg.norm(eig_vecs, axis=0)

eig_vals, eig_vecs, eig_vecs_norm

(array([3.45339765+0.j        , 2.77330117+1.46771151j,
        2.77330117-1.46771151j]),
 array([[ 0.83327121+0.j        , -0.26206044-0.31354813j,
         -0.26206044+0.31354813j],
        [ 0.455468  +0.j        , -0.78166743+0.j        ,
         -0.78166743-0.j        ],
        [ 0.31338154+0.j        , -0.21963176+0.41685708j,
         -0.21963176-0.41685708j]]),
 array([[ 0.83327121+0.j        , -0.26206044-0.31354813j,
         -0.26206044+0.31354813j],
        [ 0.455468  +0.j        , -0.78166743+0.j        ,
         -0.78166743+0.j        ],
        [ 0.31338154+0.j        , -0.21963176+0.41685708j,
         -0.21963176-0.41685708j]]))