In [2]:
# cauA
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

try:
    P_inv = np.linalg.inv(P)
except np.linalg.LinAlgError:
    P_inv = "Không khả nghịch"

P_inv


array([[ 0.5       ,  0.1       ,  0.1       , -0.3       ],
       [-0.14285714,  0.2       ,  0.05714286,  0.11428571],
       [-0.03571429, -0.05      ,  0.16428571,  0.07857143],
       [-0.32142857, -0.05      , -0.12142857,  0.50714286]])

In [6]:
# cauB

b = np.array([6, 8, 3, 7])
x = np.dot(P_inv, b)
x


array([2.        , 1.71428571, 0.42857143, 0.85714286])

In [9]:
# cauC

check = np.dot(P, x)
check


array([6., 8., 3., 7.])