In [2]:
# cauA
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

eigenvalues, eigenvectors = np.linalg.eig(Q)
eigenvalues


array([6.3553014+0.j        , 2.8223493+1.07730381j,
       2.8223493-1.07730381j])

In [10]:
# cauB
eigenvectors


array([[ 0.74846013+0.j        , -0.37423006+0.34234215j,
        -0.37423006-0.34234215j],
       [-0.18941773+0.j        ,  0.09470887+0.57433055j,
         0.09470887-0.57433055j],
       [ 0.63555359+0.j        ,  0.63555359+0.j        ,
         0.63555359-0.j        ]])

In [11]:
# cauC
normalized_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
normalized_vectors


array([[ 0.74846013+0.j        , -0.37423006+0.34234215j,
        -0.37423006-0.34234215j],
       [-0.18941773+0.j        ,  0.09470887+0.57433055j,
         0.09470887-0.57433055j],
       [ 0.63555359+0.j        ,  0.63555359+0.j        ,
         0.63555359-0.j        ]])