In [2]:
# cauA
import numpy as np
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])

x1 = np.linalg.solve(R, b)
x1


array([2.78823529, 1.52941176, 1.18823529])

In [3]:
# cauB
try:
    R_inv = np.linalg.inv(R)
    x2 = np.dot(R_inv, b)
except np.linalg.LinAlgError:
    R_inv = "Không khả nghịch"
    x2 = "Không tính được"

R_inv, x2


(array([[ 0.22352941,  0.10588235, -0.04705882],
        [-0.05882353,  0.23529412,  0.11764706],
        [ 0.02352941, -0.09411765,  0.15294118]]),
 array([2.78823529, 1.52941176, 1.18823529]))

In [4]:
# cauC
fro_norm = np.linalg.norm(R, 'fro')
fro_norm


8.0